echo "                             "
echo "                           "
echo "                               "
echo "      _____                 "
echo "  __ /     \__________________________________                 "
echo "     \______                       "
echo "            \              "
echo "             +               "
echo "              \_____        "
echo "                              "
echo "                              "

