echo "                      "
echo "                      "
echo "                      "
echo "                      "
echo "            °   O   ° "     
echo "____________|\_/-\_/|___________________ "
echo "            \+__+__+/ "
echo "                      "
echo "                      "
echo "                      "
echo "                      "
echo "                      "
