
echo "         .    _.----~~~~~~~7 "
echo "             /              ~-..-~~--..--. "
echo "       .'.'.'                              *. "
echo "         .~                                 \ "
echo "       .'                                    *. "
echo "   .   (                                       \ "
echo " '.    )                                        *. "
echo "   '  (                                       X   ~-. "
echo "       \                                             ~-~~7"
echo "        *.       __.._                                  .'"
echo "          ~-.--~~     ~--.                             / "
echo "                         ;                          .-~ "
echo "                         (                        .~ "
echo "                          *.                    .' "
echo "                            ;                   ; "
echo "                            *.                  *       _ "
echo "                             )                   )     / ) "
echo "                            (                 _.-'  .-' .' "
echo "                            *.               (      )   / "
echo "                              7             _;      < _/ "
echo "                               \           /         ~ "
echo "                                \         / "
echo "                                 *. __..-' "
echo "                                   ~ "