echo "      +                                                    . "
echo "                                     ___       . "
echo "     .                        _.--'~~ __'-. "
echo "                           ,-'     .-~  ~'-\              . "
echo "              .          .^       /       ( )      . "
echo "                    +   {_.---._ /         ~ "
echo "                        /    .  Y                            . "
echo "                      /      \_j                      + "
echo "        .             Y     ( --l__ "
echo "                      |            '-.                   . "
echo "                      |      (___     \ "
echo "              .       |        .)~-.__/             .           . "
echo "                      l        _) "
echo "     .                 \      'l "
echo "         +              \       \ "
echo "                         \       ^. "
echo "             .            ^.       '-.                 . "
echo "                            '-._      ~-.___, "
echo "                      .         '--.._____.^ "