echo "    ,-----------. "
echo "   (_\           \ "
echo "      |           |"
echo "      |           |"
echo "      |           |"
echo "      |           |"
echo "     _|           |"
echo "    (_/_____(*)___/"
echo "             \\ "
echo "              ))"
echo "              ^ "